[
    {
        "id": "PPD-3138",
        "name": "Milk",
        "quantity": "4",
        "price": "50",
        "type": "2",
        "expiry_date": "29 April 2026",
    },
    {
        "id": "PPD-8195",
        "name": "Beetroot",
        "quantity": "10",
        "price": "100",
        "type": "2",
        "expiry_date": "5 May 2026",
    },
    {
        "id": "EPD-9760",
        "name": "Samsung S24 Ultra",
        "quantity": "20",
        "price": "49999",
        "type": "3",
        "warranty": "2 Years ",
    },
    {
        "id": "EPD-4187",
        "name": "JBL Bluetooth Headphones",
        "quantity": "4",
        "price": "9999",
        "type": "3",
        "warranty": "3 Years",
    },
    {
        "id": "CPD-6752",
        "name": "Blue Shirt",
        "quantity": "14",
        "price": "999",
        "type": "4",
        "size": "M",
        "material": "Silk",
    },
    {
        "id": "PRD-4365",
        "name": "The Alchemist - By Paulo Coelho ",
        "quantity": "25",
        "price": "149",
        "type": "1",
    },
]
